### ISSUE TITLE
FetchDataAsync missing when update to 2.1.0 

### ISSUE THREAD

**Issue by hanchoong** [serilog-contrib/serilog-ui#9]
I am getting following exception when using Serilog.UI 2.1.0. Was working for 2.0.0.

`TypeLoadException: Method 'FetchDataAsync' in type 'Serilog.Ui.MsSqlServerProvider.SqlServerDataProvider' from assembly 'Serilog.Ui.MsSqlServerProvider, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

I am still using MsSqlServerProvider 1.0.6 because from 2.0.0 onward, I get a compilation error which cause my Asp.net Core 3.1 project not loading when deployed to Azure. 

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\hcchoi\.nuget\packages\serilog.ui.mssqlserverprovider\2.0.0\lib\netstandard2.0\Serilog.Ui.MsSqlServerProvider.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
`

**Comment by mo-esmp** [comment]
Hey @hanchoong 
You must update `MsSqlServerProvider` to `2.1.0` if want use `Serilog.UI` version `2.1.0` or downgrade to version `2.0.0`. Date filter added to the latest version which older provider versions no longer compatible with the latest `Serilog.UI` version.

**Comment by hanchoong** [comment]
Thanks. Noted.
